/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elektreader;

import javafx.application.Application;
import elektreader.mvc.GUI;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Application.launch(GUI.class, args);
    }
}